---
# Per environment values which override defaults in hmpps-x-ray-body-scans-ui/values.yaml

generic-service:
  ingress:
    host: x-ray-body-scans-ui.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod # k8s namespace suffix & github environment
    SENTRY_ENVIRONMENT: prod
    AUDIT_ENABLED: "false"
    INGRESS_URL: "https://x-ray-body-scans-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://dps.prison.service.justice.gov.uk"
    XRAY_BODY_SCANS_API_URL: "https://x-ray-body-scans-api.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  alertSeverity: hmpps-connect-dps-prod
