---
# Per environment values which override defaults in hmpps-x-ray-body-scans-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: x-ray-body-scans-ui-dev.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: dev      # k8s namespace suffix & github environment
    ENVIRONMENT_NAME: DEV # Phase banner tag label
    SENTRY_ENVIRONMENT: dev
    INGRESS_URL: "https://x-ray-body-scans-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin-dev.hmpps.service.justice.gov.uk'
    XRAY_BODY_SCANS_API_URL: "https://x-ray-body-scans-api-dev.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-connect-dps-non-prod
