---
# Per environment values which override defaults in hmpps-x-ray-body-scans-ui/values.yaml

generic-service:
  ingress:
    host: x-ray-body-scans-ui.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: prod # k8s namespace suffix & github environment
    SENTRY_ENVIRONMENT: prod
    INGRESS_URL: "https://x-ray-body-scans-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-connect-dps-prod
