---
# Per environment values which override defaults in hmpps-x-ray-body-scans-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: x-ray-body-scans-ui-dev.hmpps.service.justice.gov.uk

  env:
    ENVIRONMENT: dev      # k8s namespace suffix & github environment
    ENVIRONMENT_NAME: DEV # Phase banner tag label
    SENTRY_ENVIRONMENT: dev
    AUDIT_ENABLED: "false"
    INGRESS_URL: "https://x-ray-body-scans-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-dev.hmpps.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://dps-dev.prison.service.justice.gov.uk"
    XRAY_BODY_SCANS_API_URL: "https://x-ray-body-scans-api-dev.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9.30pm UTC Monday-Friday

generic-prometheus-alerts:
  alertSeverity: hmpps-connect-dps-non-prod
  businessHoursOnly: true
